### ISSUE TITLE
Make route filtering configurable?

### ISSUE THREAD

**Issue by jorvis** [perimosocordiae/route-plotter#2]
I just parsed all the runs from a year I did a lot of marathon training, but the animation generated here seems to include only the mapped area where my daily runs were located, leaving out the extended areas where my longer runs took me.  Is there a way to make this expand to show all of the run areas from the data rather than just those which seem to be the most common.  It looks like it filtered my 73 routes down to 25:

```
Parsed 73 valid routes.
Filtered to 25 routes.
Split into 12475 segments.
```

**Comment by perimosocordiae** [comment]
There are two options that control the filtering:

`--max-loop-gap N` filters out routes that don't end within N meters of where they started. If you don't care about plotting loops, you can set this to infinity: `--max-loop-gap inf`.

`--max-start-dist N` filters out routes that start more than N meters from the average starting location (i.e., your house/workplace/gym). You can increase this as needed, just like the loop gap option.

**Comment by jorvis** [comment]
Thank you, setting these definitely changed it, since a lot of our routes weren't cyclic.  Thanks!
