### ISSUE TITLE
Strange video size and corruption

### ISSUE THREAD

**Issue by ghost** [perimosocordiae/route-plotter#5]
I'm confident this is due to me not using the correct parameters but, having had a look, I'm not sure what I could have done wrong. This was the command I used:
`python route_animation.py ../activities/2017/* --save anim.mp4`
the resulting video was rather large (2432 x 1504) and very distorted and didn't extend to the boundaries of my rides, see attached screenshot. Any ideas what could be going on? Many thanks :)

![image](https://cloud.githubusercontent.com/assets/13105021/21944499/71390664-d9ce-11e6-8e7f-105f8bf7d829.png)

**Comment by ghost** [comment]
Due to the messed up setup I appear to have in #4, I suspect this is also due to that. I'll sort that and report back if it's still a problem.

**Comment by perimosocordiae** [comment]
You can try adjusting the zoom level of the background map to something smaller (with the `--zoom` option), or just scale down the background directly (with the `--scale` option).

**Comment by nobbs** [comment]
Had the same problem (white border at top and bottom); setting the aspect ratio of the plot to auto fixed that for me (see #6).

**Comment by perimosocordiae** [comment]
@Chuckatron Let me know if this solved your problem, and if not we can re-open this issue.

**Comment by ghost** [comment]
Will do :)

**Comment by ghost** [comment]
Yep, that has fixed it. Many thanks indeed!
