### ISSUE TITLE
Provide 'bitrate' parameter for animation video

### ISSUE THREAD

**Issue by ghost** [perimosocordiae/route-plotter#7]
I've noticed that it might be useful to be able to specify a bitrate for the final video generated by route_animation.py. The default bitrate appears to be 464kbps, which is pretty low and is resulting, for me anyway, in the sort of problems seen below:
![ezgif com-crop](https://cloud.githubusercontent.com/assets/13105021/22022933/f0669772-dcbb-11e6-9bdd-160a1d54e109.gif)

My knowledge of Python isn't what it could be, but a quick scan of the `matplotlib.animation` docs suggests that the `save` method can be passed a `bitrate` argument.

**Comment by perimosocordiae** [comment]
I added a `--bitrate` parameter in the latest commit: 94f5514b2578d7ed9194d694ea5a1f0ac497b3b4

**Comment by ghost** [comment]
Excellent, thanks, working great
