### ISSUE TITLE
Prevent filtering of duplicate routes

### ISSUE THREAD

**Issue by ghost** [perimosocordiae/route-plotter#8]
Currently, route-plotter very cleverly filters routes so only one instance of a given route is plotted.
```
Parsed 52 valid routes.
Filtered to 38 routes.
```
Would it be possible to allow the user to prevent this behaviour via an argument?

**Comment by perimosocordiae** [comment]
If you run it with the options `--max-loop-gap inf --max-start-dist inf`, no routes should get filtered. If that's not the case for you, please let me know!

**Comment by ghost** [comment]
That works perfectly! Thanks very much for the information.
